# =============================================================================
# mb4 Playbook
# =============================================================================
# macOS daily workstation - MacBook Pro M4
#
# Usage:
#   ansible-playbook mb4.yml
#   ansible-playbook mb4.yml --tags homebrew
# =============================================================================

- hosts: mb4
  gather_facts: true
  become: no

  vars_files:
    - vault.yml

  tasks:
    # =========================================================================
    # COMMON
    # =========================================================================
    - import_tasks: tasks/common.yml
      tags: [common]

    # =========================================================================
    # HOMEBREW
    # =========================================================================
    - import_tasks: tasks/homebrew.yml
      tags: [homebrew, packages]

    # =========================================================================
    # SYNCTHING
    # =========================================================================
    - import_tasks: tasks/syncthing-macos.yml
      tags: [syncthing]

    # =========================================================================
    # MACKUP
    # =========================================================================
    - import_tasks: tasks/mackup.yml
      tags: [mackup]

    # =========================================================================
    # HOSTS - Local DNS entries for NSA services
    # =========================================================================
    - import_tasks: tasks/hosts-macos.yml
      tags: [hosts, dns]

    # =========================================================================
    # DOCKER - Local development containers via Colima
    # =========================================================================
    - import_tasks: tasks/docker-macos.yml
      tags: [docker, colima]
