# =============================================================================
# mkt Playbook (MikroTik hAP ax³ Router)
# =============================================================================
# Network router configuration: PPPoE WAN, DHCP, firewall, WiFi
#
# Usage:
#   ansible-playbook mkt.yml
#   ansible-playbook mkt.yml --tags dhcp
#   ansible-playbook mkt.yml --check --diff
# =============================================================================

- name: Configure MikroTik Router
  hosts: mkt
  gather_facts: false

  vars_files:
    - vault.yml

  tasks:
    # =========================================================================
    # IDENTITY
    # =========================================================================
    - import_tasks: tasks/mikrotik/identity.yml
      tags: [identity]

    # =========================================================================
    # BRIDGE (LAN)
    # =========================================================================
    - import_tasks: tasks/mikrotik/bridge.yml
      tags: [bridge, network]

    # =========================================================================
    # IP ADDRESS
    # =========================================================================
    - import_tasks: tasks/mikrotik/ip-address.yml
      tags: [ip, network]

    # =========================================================================
    # PPPOE (WAN)
    # =========================================================================
    - import_tasks: tasks/mikrotik/pppoe.yml
      tags: [pppoe, wan]

    # =========================================================================
    # DHCP SERVER
    # =========================================================================
    - import_tasks: tasks/mikrotik/dhcp-server.yml
      tags: [dhcp]

    # =========================================================================
    # FIREWALL NAT
    # =========================================================================
    - import_tasks: tasks/mikrotik/firewall-nat.yml
      tags: [firewall, nat]

    # =========================================================================
    # FIREWALL FILTER
    # =========================================================================
    - import_tasks: tasks/mikrotik/firewall-filter.yml
      tags: [firewall, filter]

    # =========================================================================
    # WIFI
    # =========================================================================
    - import_tasks: tasks/mikrotik/wifi.yml
      tags: [wifi, wireless]

    # =========================================================================
    # GUEST NETWORK (isolated VLAN)
    # =========================================================================
    - import_tasks: tasks/mikrotik/guest-network.yml
      tags: [guest, wifi, wireless]

    # =========================================================================
    # SERVICES
    # =========================================================================
    - import_tasks: tasks/mikrotik/services.yml
      tags: [services, security]
